"""
Reads results/*.json (written by src/eval/run_eval.save_results) and bakes
them into dashboard/data.js as a plain JS object, so index.html can be opened
directly (file://) with no local server or build step needed.

Run this after each Colab run that produces new results:
    python dashboard/build_data.py
"""

import json
import os
import glob

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")
OUT_PATH = os.path.join(os.path.dirname(__file__), "data.js")


def main():
    all_results = {}
    for path in sorted(glob.glob(os.path.join(RESULTS_DIR, "*.json"))):
        with open(path) as f:
            data = json.load(f)
        method = data.get("method", os.path.splitext(os.path.basename(path))[0])
        all_results[method] = data

    if not all_results:
        print(f"no *.json files found in {RESULTS_DIR} -- run the Colab pipeline first")
        return

    with open(OUT_PATH, "w") as f:
        f.write("// auto-generated by dashboard/build_data.py -- do not edit by hand\n")
        f.write(f"window.FORGETPROOF_RESULTS = {json.dumps(all_results, indent=2)};\n")

    print(f"wrote {len(all_results)} method(s) -> {OUT_PATH}")


if __name__ == "__main__":
    main()
