// auto-generated by dashboard/build_data.py -- do not edit by hand
window.FORGETPROOF_RESULTS = {
  "grad_ascent": {
    "method": "grad_ascent",
    "relearning_attack": {
      "pre_attack_holdout_loss": 95.8921875,
      "post_attack_holdout_loss": NaN,
      "recovery_score": 1,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 95.7753125,
      "unseen_mean_loss": 94.50375,
      "gap": -1.2715625000000017,
      "leak_score": 0
    },
    "rephrase_extraction": {
      "leak_rate": 0
    },
    "representation_probe": {
      "probe_accuracy": 0.6666666666666666,
      "chance_accuracy": 0.1,
      "above_chance": 0.5666666666666667,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 106.35625
  },
  "grad_diff": {
    "method": "grad_diff",
    "relearning_attack": {
      "pre_attack_holdout_loss": 4.0948974609375,
      "post_attack_holdout_loss": 2.4492919921875,
      "recovery_score": 0.4018673201094637,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 4.12750244140625,
      "unseen_mean_loss": 8.0503125,
      "gap": 3.9228100585937504,
      "leak_score": 0.4872866809324172
    },
    "rephrase_extraction": {
      "leak_rate": 0.04
    },
    "representation_probe": {
      "probe_accuracy": 0.9333333333333333,
      "chance_accuracy": 0.1,
      "above_chance": 0.8333333333333334,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 3.093447265625
  },
  "mlp_breaking": {
    "method": "mlp_breaking",
    "relearning_attack": {
      "pre_attack_holdout_loss": 3.084332275390625,
      "post_attack_holdout_loss": 2.4230621337890623,
      "recovery_score": 0.21439653142358467,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.141346435546875,
      "unseen_mean_loss": 7.4398828125,
      "gap": 4.298536376953125,
      "leak_score": 0.5777693661694521
    },
    "rephrase_extraction": {
      "leak_rate": 0.06
    },
    "representation_probe": {
      "probe_accuracy": 0.9,
      "chance_accuracy": 0.1,
      "above_chance": 0.8,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.510634765625
  },
  "mlp_breaking_mcu": {
    "method": "mlp_breaking_mcu",
    "relearning_attack": {
      "pre_attack_holdout_loss": 3.057562255859375,
      "post_attack_holdout_loss": 2.426446533203125,
      "recovery_score": 0.20641140550672615,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.1441552734375,
      "unseen_mean_loss": 7.4287109375,
      "gap": 4.2845556640625,
      "leak_score": 0.5767562771131852
    },
    "rephrase_extraction": {
      "leak_rate": 0.06
    },
    "representation_probe": {
      "probe_accuracy": 0.9,
      "chance_accuracy": 0.1,
      "above_chance": 0.8,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.504560546875
  },
  "npo": {
    "method": "npo",
    "relearning_attack": {
      "pre_attack_holdout_loss": 2.96800537109375,
      "post_attack_holdout_loss": 2.440960693359375,
      "recovery_score": 0.1775753786928466,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.01687744140625,
      "unseen_mean_loss": 7.25802734375,
      "gap": 4.24114990234375,
      "leak_score": 0.5843392014768131
    },
    "rephrase_extraction": {
      "leak_rate": 0.08
    },
    "representation_probe": {
      "probe_accuracy": 0.9333333333333333,
      "chance_accuracy": 0.1,
      "above_chance": 0.8333333333333334,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.37927734375
  },
  "npo_mcu": {
    "method": "npo_mcu",
    "relearning_attack": {
      "pre_attack_holdout_loss": 3.122772216796875,
      "post_attack_holdout_loss": 2.4457061767578123,
      "recovery_score": 0.21681569869145,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.20739501953125,
      "unseen_mean_loss": 8.53955078125,
      "gap": 5.3321557617187505,
      "leak_score": 0.6244070558636858
    },
    "rephrase_extraction": {
      "leak_rate": 0.06
    },
    "representation_probe": {
      "probe_accuracy": 0.9,
      "chance_accuracy": 0.1,
      "above_chance": 0.8,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.5396875
  },
  "rmu": {
    "method": "rmu",
    "relearning_attack": {
      "pre_attack_holdout_loss": 3.01138916015625,
      "post_attack_holdout_loss": 2.4172119140625,
      "recovery_score": 0.19731001690360084,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.079305419921875,
      "unseen_mean_loss": 7.2528515625,
      "gap": 4.173546142578125,
      "leak_score": 0.5754352073268596
    },
    "rephrase_extraction": {
      "leak_rate": 0.06
    },
    "representation_probe": {
      "probe_accuracy": 0.9333333333333333,
      "chance_accuracy": 0.1,
      "above_chance": 0.8333333333333334,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.490556640625
  },
  "rmu_mcu": {
    "method": "rmu_mcu",
    "relearning_attack": {
      "pre_attack_holdout_loss": 3.11839599609375,
      "post_attack_holdout_loss": 2.4168670654296873,
      "recovery_score": 0.22496467143455515,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.19432373046875,
      "unseen_mean_loss": 7.44853515625,
      "gap": 4.25421142578125,
      "leak_score": 0.5711473916064662
    },
    "rephrase_extraction": {
      "leak_rate": 0.06
    },
    "representation_probe": {
      "probe_accuracy": 0.9,
      "chance_accuracy": 0.1,
      "above_chance": 0.8,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.5508984375
  }
};
