// auto-generated by dashboard/build_data.py -- do not edit by hand
window.FORGETPROOF_RESULTS = {
  "grad_ascent": {
    "method": "grad_ascent",
    "relearning_attack": {
      "pre_attack_holdout_loss": 129.51382417678832,
      "post_attack_holdout_loss": 3.906207504868507,
      "recovery_score": 0.9698394551338668,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 129.35291923522948,
      "unseen_mean_loss": 128.33630271911622,
      "gap": -1.0166165161132596,
      "leak_score": 0
    },
    "rephrase_extraction": {
      "leak_rate": 0
    },
    "representation_probe": {
      "probe_accuracy": 0.7666666666666667,
      "chance_accuracy": 0.1,
      "above_chance": 0.6666666666666667,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 141.92388671875
  },
  "grad_diff": {
    "method": "grad_diff",
    "relearning_attack": {
      "pre_attack_holdout_loss": 4.111749144643545,
      "post_attack_holdout_loss": 2.4697523452341557,
      "recovery_score": 0.3993426499640549,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 4.1624628227949145,
      "unseen_mean_loss": 7.982694511413574,
      "gap": 3.8202316886186596,
      "leak_score": 0.4785641844563301
    },
    "rephrase_extraction": {
      "leak_rate": 0.04
    },
    "representation_probe": {
      "probe_accuracy": 0.9333333333333333,
      "chance_accuracy": 0.1,
      "above_chance": 0.8333333333333334,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 3.0829239070415495
  },
  "mlp_breaking": {
    "method": "mlp_breaking",
    "relearning_attack": {
      "pre_attack_holdout_loss": 3.1492677219212055,
      "post_attack_holdout_loss": 2.440015795454383,
      "recovery_score": 0.2252116965254845,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.205718120336533,
      "unseen_mean_loss": 7.538525021076202,
      "gap": 4.332806900739669,
      "leak_score": 0.5747552589698928
    },
    "rephrase_extraction": {
      "leak_rate": 0.06
    },
    "representation_probe": {
      "probe_accuracy": 0.9,
      "chance_accuracy": 0.1,
      "above_chance": 0.8,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.5490443336963655
  },
  "mlp_breaking_mcu": {
    "method": "mlp_breaking_mcu",
    "relearning_attack": {
      "pre_attack_holdout_loss": 3.124360231310129,
      "post_attack_holdout_loss": 2.4463295016437767,
      "recovery_score": 0.21701426195084927,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.2116005916893484,
      "unseen_mean_loss": 7.525381593704224,
      "gap": 4.313781002014876,
      "leak_score": 0.5732308652127102
    },
    "rephrase_extraction": {
      "leak_rate": 0.06
    },
    "representation_probe": {
      "probe_accuracy": 0.9,
      "chance_accuracy": 0.1,
      "above_chance": 0.8,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.544242191314697
  },
  "npo": {
    "method": "npo",
    "relearning_attack": {
      "pre_attack_holdout_loss": 2.9654261738061907,
      "post_attack_holdout_loss": 2.4528098944574594,
      "recovery_score": 0.17286428638038787,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.041319317519665,
      "unseen_mean_loss": 7.3477989768981935,
      "gap": 4.306479659378528,
      "leak_score": 0.5860911101294811
    },
    "rephrase_extraction": {
      "leak_rate": 0.1
    },
    "representation_probe": {
      "probe_accuracy": 0.9333333333333333,
      "chance_accuracy": 0.1,
      "above_chance": 0.8333333333333334,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.369363830089569
  },
  "npo_mcu": {
    "method": "npo_mcu",
    "relearning_attack": {
      "pre_attack_holdout_loss": 3.27747655287385,
      "post_attack_holdout_loss": 2.4353710778057573,
      "recovery_score": 0.25693714706507775,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.289759791493416,
      "unseen_mean_loss": 8.806549365520477,
      "gap": 5.516789574027061,
      "leak_score": 0.626441679374043
    },
    "rephrase_extraction": {
      "leak_rate": 0.02
    },
    "representation_probe": {
      "probe_accuracy": 0.9,
      "chance_accuracy": 0.1,
      "above_chance": 0.8,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.621608644723892
  },
  "rmu": {
    "method": "rmu",
    "relearning_attack": {
      "pre_attack_holdout_loss": 3.0771963976323606,
      "post_attack_holdout_loss": 2.436595210060477,
      "recovery_score": 0.2081768937675773,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.142207833826542,
      "unseen_mean_loss": 7.3267207527160645,
      "gap": 4.1845129188895225,
      "leak_score": 0.5711303951823598
    },
    "rephrase_extraction": {
      "leak_rate": 0.06
    },
    "representation_probe": {
      "probe_accuracy": 0.9,
      "chance_accuracy": 0.1,
      "above_chance": 0.8,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.530958141088486
  },
  "rmu_mcu": {
    "method": "rmu_mcu",
    "relearning_attack": {
      "pre_attack_holdout_loss": 3.193530744314194,
      "post_attack_holdout_loss": 2.4360357869416474,
      "recovery_score": 0.2371967010874096,
      "n_holdout": 80,
      "n_relearn": 320
    },
    "membership_inference": {
      "forget_mean_loss": 3.268058413565159,
      "unseen_mean_loss": 7.517870700359344,
      "gap": 4.249812286794185,
      "leak_score": 0.5652946766683616
    },
    "rephrase_extraction": {
      "leak_rate": 0.06
    },
    "representation_probe": {
      "probe_accuracy": 0.9,
      "chance_accuracy": 0.1,
      "above_chance": 0.8,
      "n_entities": 10,
      "n_examples": 100,
      "layer": -1
    },
    "model_utility_loss": 2.598976141214371
  }
};
